batch_size: 1024
clip_coef: 0.1
ent_coef: 0.01
env_name: seaquest
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.00025
minibatch_size: 256
mode: logic
num_envs: 8
num_iterations: 9765
num_steps: 128
recover: false
rules: default1
save_steps: 1000000
seed: 8
total_timesteps: 10000000
update_epochs: 4
